import type { Metadata } from "next";

import "./style/globals.css";
import { ThemeProvider } from "../providers/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import Header from "@/components/Header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className="bg-white text-black">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />

          <div className="flex min-h-screen flex-col">
            <main className="flex flex-1 flex-col px-4 pt-10  xl:px-8">
              {children}

            </main>
            <Toaster />


          </div>

        </ThemeProvider>
      </body>
    </html>
  );
}
